[package]
name = "rts-coding-battle"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy-tokio-tasks = "0.15"
bevy_common_assets = { version = "0.12.0", features = ["ron"] }
bincode = "1.3.3"
serde = "1.0.217"
tokio = { version = "1.43.0", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
] }
