[package]
name = "rts-coding-battle"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy-inspector-egui = "0.29.1"
bevy_common_assets = { version = "0.12.0", features = ["ron"] }
bevy_renet = "1"
bincode = "1.3.3"
crossbeam-channel = "0.5.14"
serde = "1.0.217"
serde_json = "1.0.137"
