[workspace]
resolver = "2"

[package]
name = "rts-coding-battle"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["serialize"] }
bevy-inspector-egui = "0.29.1"
bevy_common_assets = { version = "0.12.0", features = ["ron"] }
bevy_renet = "1"
bincode = "1.3.3"
crossbeam-channel = "0.5.14"
serde = "1.0.217"
serde_json = "1.0.137"

[dev-dependencies]
bevy_dev_tools = { version = "0.15" }
bevy = { version = "0.15", features = ["serialize", "bevy_dev_tools"] }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable a lot of optimization in release mode
[profile.release]
codegen-units = 1
lto = "thin"

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
