[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_common_assets = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["bevy_debug"]
bevy_debug = ["bevy/bevy_dev_tools"]
