[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_common_assets = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
server = [
    "bevy/bevy_state",
    "bevy/bevy_asset",
    "bevy/bevy_color",
    "bevy/serialize",
    "bevy/multi_threaded",
]
