[alias]
# Build with default features
b = "build"
# Run with default features
r = "run"
# Build with release optimizations
br = "build --release --no-default-features"
# Run with release optimizations
rr = "run --release --no-default-features"
