[package]
name = "spectator_client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_common_assets = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
spectator_client = ["bevy/default"]
