name: Deploy Rust App

on:
  push:
    branches:
      - master  # Adjust this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build the application
        run: cargo br

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: target/release/your-binary-name

      - name: Deploy to Linode
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          LINODE_IP: "139.162.177.39"  # Replace with your Linode server IP
          USER: "root"        # Adjust if necessary
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key target/release/tank-coding-battle $USER@$LINODE_IP:/home/$USER/
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$LINODE_IP "pkill -f tank-coding-battle || true && nohup /home/$USER/tank-coding-battle &"

      - name: Clean up
        run: rm -f private_key
